#! /bin/sh

nickname=$1; export nickname

(
    # UCSPI wants input on FD 7, and sets $PROTO
    [ -n "$PROTO" ] && exec 1>&7
    echo "NICK $1"
    echo "USER $1 $1 $1 :I'm a little printf, short and stdout."
)

mkfifo -m 0600 $1.fifo

exec ./dispatch -f $1.fifo ./irc ./$1-handler
