#! /bin/sh

db=$1; shift
text="$1"

lookup () {
    if ! cdb -q -m $db "$1"; then
        t="$1"
        while [ "$t" != "$n" ]; do
            n=$t
            t=${n%[?!. ]}
        done
        if [ "$t" != "$1" ]; then
            cdb -q -m $db "$t"
        fi
    fi
}

db_append () {
    (printf "+%d,%d:%s->%s\n" ${#1} ${#2} "$1" "$2"; cdb -d $db) | cdb -c $db
    echo "Okay, $sender, I added a factoid to $1."
}

nickname=${nickname:-infobot}
args=${text#* }

case "$text" in
    !h*)
        cat <<EOF
!stats                       Show statistics
!list KEY                    List all factoids stored for KEY
!append KEY += VALUE         Add VALUE to KEY's factoids
!remove KEY -= VALUE         Remove *VALUE* from KEY's factoids
!forget KEY                  Remove all factoids for KEY
EOF
        ;;
    !s*)
        cdb -s $db | head -n 1
        ;;
    !l*)
        printf "factoids for \"%s\": " "$args"
        cdb -q -m $db "$args" | awk '{printf("|%s", $0);}'
        echo
        ;;
    $nickname:\ *\ is\ *)
        s=${text#$nickname: }
        db_append "${s%% is *}" "${s#* is }"
        ;;
    !a*)
	db_append "${args% +=*}" "${args#*+= }"
        ;;
    !r*)
	key=${args% -=*}
	val=${args#*-= }
        re=":$key->.*$val"
        n=$(cdb -d $db | grep -c "$re")
        if [ $n -gt 0 ]; then
            cdb -d $db | grep -a -v ":$key->.*$val" | cdb -c $db
            echo "Okay, $sender, I removed $n factoids from $key"
        else
            echo "Nothing matched, $sender."
        fi
        ;;
    !forget\ *)
        cdb -d $db | grep -a -F -v ":$args->" | cdb -c $db
        echo "I removed all factoids from $args"
        ;;
    *)
        resp=$(lookup "$text" | shuf -n 1 | sed "s/\$sender/$sender/")
        case "$resp" in
            "")
                exit 1
                ;;
            ''*)
                echo "Someone's up to no good!"
                ;;
            '\'*)
                printf "%s\n" "${resp#\\}"
                ;;
            :*)
                printf '\001ACTION %s\001\n' "${resp#:}"
                ;;
            *)
                echo "It's been said that $text is $resp"
                ;;
        esac
        ;;
esac
