#! /bin/sh -e

botdir=$1
ircdir=$(dirname $0)
export botdir ircdir

if [ ! -d "$botdir" ]; then
    exec 1>&2
    echo "Usage: $0 BOTDIRECTORY"
    exit 1
fi

while true; do
    $botdir/connect $ircdir/connect-handler $botdir
    sleep 5
done
